import type { PhaseMeta, Resource } from "@/lib/types";

/**
 * The course map. Lessons live in content/<phase-slug>/NN-<lesson-slug>.md;
 * this file holds each phase's description, outcomes and resources.
 */

export const toolkit: Resource[] = [
  {
    title: "Python (official installer)",
    url: "https://www.python.org/downloads/",
    type: "tool",
    free: true,
    note: "Install Python 3.13 or newer on your own computer once you outgrow the in-browser runner (Phase 2).",
  },
  {
    title: "Visual Studio Code",
    url: "https://code.visualstudio.com/",
    type: "tool",
    free: true,
    note: "The editor most Python developers use. Add the official Python extension from Microsoft.",
  },
  {
    title: "VS Code Python extension",
    url: "https://marketplace.visualstudio.com/items?itemName=ms-python.python",
    type: "tool",
    free: true,
    note: "Run, debug and lint Python inside VS Code.",
  },
  {
    title: "uv (Python package and project manager)",
    url: "https://docs.astral.sh/uv/",
    type: "tool",
    free: true,
    note: "Creates virtual environments and installs packages very fast. Used from Phase 2 onwards.",
  },
  {
    title: "Google Colab",
    url: "https://colab.research.google.com/",
    type: "tool",
    free: true,
    note: "Free Jupyter notebooks in the browser, with GPUs. Needed for the deep learning phase.",
  },
  {
    title: "Kaggle",
    url: "https://www.kaggle.com/",
    type: "practice",
    free: true,
    note: "Datasets, free notebooks, short courses and competitions to build a public portfolio.",
  },
  {
    title: "Git and GitHub",
    url: "https://git-scm.com/book/en/v2",
    type: "book",
    free: true,
    note: "Pro Git, free online. Commit every exercise you do outside this site to your own repo.",
  },
  {
    title: "Python Tutor",
    url: "https://pythontutor.com/",
    type: "tool",
    free: true,
    note: "Step through code line by line and watch variables change. Brilliant when something confuses you.",
  },
];

export const phases: PhaseMeta[] = [
  {
    slug: "python-foundations",
    number: 1,
    title: "Python Foundations",
    tagline: "Write your first programs and think like a programmer.",
    description:
      "Start from zero: values, variables, decisions, loops, collections, functions, errors and files. Every concept is practised with small exercises, and the phase ends with a betting toolkit that converts odds, measures the bookmaker's margin and spots value.",
    weeks: "Weeks 1–4",
    outcomes: [
      "Read and write Python programs of 50–100 lines with confidence",
      "Choose between lists, dictionaries, tuples and sets for a problem",
      "Break problems into small, tested functions",
      "Read a traceback and fix the bug instead of guessing",
      "Load and save CSV and JSON files",
    ],
    resources: [
      {
        title: "Kaggle Learn: Python",
        url: "https://www.kaggle.com/learn/python",
        type: "course",
        free: true,
        note: "Short, hands-on lessons that lead straight into Kaggle's pandas and ML courses. A great companion to this phase.",
      },
      {
        title: "CS50's Introduction to Programming with Python (Harvard)",
        url: "https://cs50.harvard.edu/python/",
        type: "course",
        free: true,
        note: "Longer and more thorough, with excellent lectures and problem sets. Use it if you want a second explanation of anything here.",
      },
      {
        title: "The official Python tutorial",
        url: "https://docs.python.org/3/tutorial/",
        type: "docs",
        free: true,
        note: "Dry but precise. Get used to reading the official docs early: professionals live in them.",
      },
      {
        title: "Automate the Boring Stuff with Python (Al Sweigart)",
        url: "https://automatetheboringstuff.com/",
        type: "book",
        free: true,
        note: "Free to read online. Very practical: files, spreadsheets, web scraping and automation projects.",
      },
      {
        title: "Python Crash Course, 3rd edition (Eric Matthes)",
        url: "https://nostarch.com/python-crash-course-3rd-edition",
        type: "book",
        free: false,
        note: "The best-selling beginner book. Worth buying if you like learning from a printed book.",
      },
      {
        title: "Corey Schafer's Python tutorials",
        url: "https://www.youtube.com/@coreyms",
        type: "video",
        free: true,
        note: "Clear, no-nonsense videos on almost every Python topic in this phase and the next.",
      },
      {
        title: "Exercism: Python track",
        url: "https://exercism.org/tracks/python",
        type: "practice",
        free: true,
        note: "Hundreds of extra exercises with free mentor feedback. Do a few each week after this phase.",
      },
    ],
  },
  {
    slug: "professional-python",
    number: 2,
    title: "Professional Python",
    tagline: "Write code other people (and future you) can trust.",
    description:
      "Move from scripts to software: classes, dataclasses, iterators, generators, decorators, type hints, testing with pytest, virtual environments and project structure. You'll set up Python on your own computer and build a tested bankroll tracker.",
    weeks: "Weeks 5–7",
    outcomes: [
      "Model real things with classes and dataclasses",
      "Use generators, decorators and context managers, and know when they help",
      "Add type hints and run a type checker",
      "Write pytest tests before and after you write code",
      "Set up a project with a virtual environment, dependencies, linting and git",
    ],
    resources: [
      {
        title: "Real Python",
        url: "https://realpython.com/",
        type: "article",
        free: true,
        note: "In-depth tutorials on every intermediate topic (OOP, decorators, testing, packaging). Some content needs a subscription.",
      },
      {
        title: "Fluent Python, 2nd edition (Luciano Ramalho)",
        url: "https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/",
        type: "book",
        free: false,
        note: "The book that turns intermediate Python programmers into experts. Read it slowly over months.",
      },
      {
        title: "Effective Python, 3rd edition (Brett Slatkin)",
        url: "https://effectivepython.com/",
        type: "book",
        free: false,
        note: "Short, specific rules for writing better Python. Easy to dip into.",
      },
      {
        title: "pytest documentation",
        url: "https://docs.pytest.org/",
        type: "docs",
        free: true,
        note: "The testing framework used across the Python world. Start with “Get started”.",
      },
      {
        title: "PEP 8: Style Guide for Python Code",
        url: "https://peps.python.org/pep-0008/",
        type: "docs",
        free: true,
        note: "How Python code should look. Ruff (below) checks most of it for you.",
      },
      {
        title: "typing module and mypy",
        url: "https://mypy.readthedocs.io/en/stable/getting_started.html",
        type: "docs",
        free: true,
        note: "Type hints catch bugs before you run the code. mypy's getting-started guide is the gentlest intro.",
      },
      {
        title: "Ruff (linter and formatter)",
        url: "https://docs.astral.sh/ruff/",
        type: "tool",
        free: true,
        note: "One fast tool that formats your code and catches common mistakes.",
      },
      {
        title: "Python Packaging User Guide",
        url: "https://packaging.python.org/en/latest/tutorials/packaging-projects/",
        type: "docs",
        free: true,
        note: "How pyproject.toml works and how to share your own package.",
      },
    ],
  },
  {
    slug: "data-analysis",
    number: 3,
    title: "Data Analysis with NumPy, pandas & Matplotlib",
    tagline: "Load, clean, explore and chart real datasets.",
    description:
      "The tools every data scientist uses daily. Fast numerical arrays with NumPy, tables with pandas (filtering, grouping, joining, time series) and charts with Matplotlib. The project analyses a full football season: home advantage, bookmaker margins and team form.",
    weeks: "Weeks 8–11",
    outcomes: [
      "Replace slow loops with vectorised NumPy operations",
      "Load, filter, group, join and reshape tables with pandas",
      "Clean messy data: missing values, wrong types, dates and duplicates",
      "Build rolling and lagged features without leaking the future",
      "Make clear charts that answer a question",
    ],
    resources: [
      {
        title: "Python for Data Analysis, 3rd edition (Wes McKinney)",
        url: "https://wesmckinney.com/book/",
        type: "book",
        free: true,
        note: "Written by the creator of pandas, and free to read online. The reference for this phase.",
      },
      {
        title: "Python Data Science Handbook (Jake VanderPlas)",
        url: "https://jakevdp.github.io/PythonDataScienceHandbook/",
        type: "book",
        free: true,
        note: "Free online. Excellent chapters on NumPy, pandas, Matplotlib and an intro to scikit-learn.",
      },
      {
        title: "Kaggle Learn: Pandas",
        url: "https://www.kaggle.com/learn/pandas",
        type: "course",
        free: true,
        note: "Quick exercises on real datasets.",
      },
      {
        title: "Kaggle Learn: Data Cleaning",
        url: "https://www.kaggle.com/learn/data-cleaning",
        type: "course",
        free: true,
        note: "Missing values, scaling, dates and inconsistent text.",
      },
      {
        title: "Kaggle Learn: Data Visualization",
        url: "https://www.kaggle.com/learn/data-visualization",
        type: "course",
        free: true,
        note: "Charts with seaborn, built on Matplotlib.",
      },
      {
        title: "NumPy: the absolute basics for beginners",
        url: "https://numpy.org/doc/stable/user/absolute_beginners.html",
        type: "docs",
        free: true,
        note: "The official beginner guide to arrays.",
      },
      {
        title: "pandas: getting started tutorials",
        url: "https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html",
        type: "docs",
        free: true,
        note: "Official short tutorials. pandas 3 changed some defaults (copy-on-write, string dtype). This course uses pandas 3.",
      },
      {
        title: "Matplotlib tutorials",
        url: "https://matplotlib.org/stable/tutorials/index.html",
        type: "docs",
        free: true,
        note: "Start with “Quick start guide”.",
      },
      {
        title: "Football-Data.co.uk",
        url: "https://www.football-data.co.uk/data.php",
        type: "tool",
        free: true,
        note: "Free historical results and bookmaker odds for many leagues. Our lessons use a synthetic dataset with the same columns, so you can switch to the real data easily.",
      },
    ],
  },
  {
    slug: "math-for-ml",
    number: 4,
    title: "Math & Statistics for ML",
    tagline: "The probability, statistics, linear algebra and calculus that ML is built on.",
    description:
      "No proofs, lots of code. Probability and expected value, distributions (including Poisson, which models football goals), variance and simulation, hypothesis tests, vectors and matrices, and gradient descent written from scratch. The project asks the question that matters most for betting: is a winning record skill or luck?",
    weeks: "Weeks 12–15 (in parallel with Phase 3 if you like)",
    outcomes: [
      "Calculate expected value and variance, and explain why both matter for betting",
      "Use the binomial, Poisson and normal distributions with scipy.stats",
      "Simulate random processes with Monte Carlo methods",
      "Test whether a result could be luck, and size a sample properly",
      "Do vector and matrix maths in NumPy and implement gradient descent",
    ],
    resources: [
      {
        title: "Khan Academy: Statistics and probability",
        url: "https://www.khanacademy.org/math/statistics-probability",
        type: "course",
        free: true,
        note: "Short videos and practice for every statistics concept in this phase.",
      },
      {
        title: "StatQuest with Josh Starmer",
        url: "https://www.youtube.com/@statquest",
        type: "video",
        free: true,
        note: "The friendliest explanations of statistics and ML concepts on the internet.",
      },
      {
        title: "3Blue1Brown: Essence of Linear Algebra",
        url: "https://www.3blue1brown.com/topics/linear-algebra",
        type: "video",
        free: true,
        note: "Beautiful visual intuition for vectors and matrices. Watch before the linear algebra lesson.",
      },
      {
        title: "3Blue1Brown: Essence of Calculus",
        url: "https://www.3blue1brown.com/topics/calculus",
        type: "video",
        free: true,
        note: "Derivatives explained visually. Enough calculus for gradient descent.",
      },
      {
        title: "Seeing Theory (Brown University)",
        url: "https://seeing-theory.brown.edu/",
        type: "tool",
        free: true,
        note: "Interactive visualisations of probability and statistics.",
      },
      {
        title: "Think Stats, 3rd edition (Allen Downey)",
        url: "https://allendowney.github.io/ThinkStats/",
        type: "book",
        free: true,
        note: "Statistics taught through Python code instead of formulas. Free online.",
      },
      {
        title: "Mathematics for Machine Learning (Deisenroth, Faisal, Ong)",
        url: "https://mml-book.github.io/",
        type: "book",
        free: true,
        note: "The free reference book when you want the full maths. Dip into it; don't read it cover to cover yet.",
      },
      {
        title: "scipy.stats reference",
        url: "https://docs.scipy.org/doc/scipy/reference/stats.html",
        type: "docs",
        free: true,
        note: "Distributions and statistical tests.",
      },
    ],
  },
  {
    slug: "machine-learning",
    number: 5,
    title: "Machine Learning with scikit-learn",
    tagline: "Train, evaluate and improve real models.",
    description:
      "The core of the course. How models learn, linear and logistic regression (first from scratch, then with scikit-learn), honest evaluation, overfitting and cross-validation, trees, random forests, gradient boosting, clustering, PCA, pipelines and tuning. The project predicts match outcomes and compares your probabilities with the bookmaker's.",
    weeks: "Weeks 16–21",
    outcomes: [
      "Frame a problem as regression, classification or clustering",
      "Train and compare models with scikit-learn and pick the right metric",
      "Diagnose overfitting and fix it with regularisation and cross-validation",
      "Build preprocessing pipelines that can't leak test data",
      "Tune gradient boosting models and explain what they learned",
    ],
    resources: [
      {
        title: "Machine Learning Specialization (Andrew Ng, DeepLearning.AI)",
        url: "https://www.coursera.org/specializations/machine-learning-introduction",
        type: "course",
        free: true,
        note: "The classic ML course, updated for Python. Free to audit. Take it alongside this phase.",
      },
      {
        title: "Hands-On Machine Learning (Aurélien Géron), code and notebooks",
        url: "https://github.com/ageron/handson-ml3",
        type: "book",
        free: false,
        note: "The most practical ML book. The notebooks are free on GitHub; the book itself is paid.",
      },
      {
        title: "An Introduction to Statistical Learning, with Python (ISLP)",
        url: "https://www.statlearning.com/",
        type: "book",
        free: true,
        note: "Free PDF. Explains why the algorithms work, with Python labs.",
      },
      {
        title: "scikit-learn user guide",
        url: "https://scikit-learn.org/stable/user_guide.html",
        type: "docs",
        free: true,
        note: "Some of the best documentation in open source. Each model has examples.",
      },
      {
        title: "Kaggle Learn: Intro to Machine Learning",
        url: "https://www.kaggle.com/learn/intro-to-machine-learning",
        type: "course",
        free: true,
        note: "Fast practice with decision trees and random forests.",
      },
      {
        title: "Kaggle Learn: Intermediate Machine Learning",
        url: "https://www.kaggle.com/learn/intermediate-machine-learning",
        type: "course",
        free: true,
        note: "Missing values, categorical data, pipelines, cross-validation, XGBoost, leakage.",
      },
      {
        title: "Kaggle Learn: Feature Engineering",
        url: "https://www.kaggle.com/learn/feature-engineering",
        type: "course",
        free: true,
        note: "Where most of a model's edge comes from.",
      },
      {
        title: "Google Machine Learning Crash Course",
        url: "https://developers.google.com/machine-learning/crash-course",
        type: "course",
        free: true,
        note: "Short modules with interactive visualisations.",
      },
      {
        title: "Kaggle: Titanic competition",
        url: "https://www.kaggle.com/competitions/titanic",
        type: "practice",
        free: true,
        note: "Everyone's first competition. Submit a model once you finish this phase.",
      },
    ],
  },
  {
    slug: "applied-ml",
    number: 6,
    title: "Applied ML: Time Series, Betting & Trading",
    tagline: "Build models on time-ordered data, and evaluate them honestly.",
    description:
      "Where most models fail in practice. Walk-forward validation, data leakage, Elo ratings and form features, Poisson and Dixon–Coles goal models, value betting, staking and backtesting, forex returns and transaction costs, calibration, and saving and tracking models. The project is a complete value-betting backtester.",
    weeks: "Weeks 22–26",
    outcomes: [
      "Validate models on time-ordered data without peeking at the future",
      "Find and remove data leakage",
      "Build Elo ratings and Poisson goal models from scratch",
      "Backtest a strategy with costs, and report ROI, drawdown and Sharpe ratio",
      "Calibrate probabilities, and save, version and reload models",
    ],
    resources: [
      {
        title: "Advances in Financial Machine Learning (Marcos López de Prado)",
        url: "https://www.wiley.com/en-us/Advances+in+Financial+Machine+Learning-p-9781119482086",
        type: "book",
        free: false,
        note: "The book on why financial ML backtests lie, and how to make them honest. Advanced; read after this phase.",
      },
      {
        title: "Forecasting: Principles and Practice (Hyndman & Athanasopoulos)",
        url: "https://otexts.com/fpp3/",
        type: "book",
        free: true,
        note: "Free online, and the best introduction to time-series thinking. Examples are in R, but the ideas transfer directly.",
      },
      {
        title: "Machine Learning for Algorithmic Trading (Stefan Jansen), code",
        url: "https://github.com/stefan-jansen/machine-learning-for-trading",
        type: "book",
        free: false,
        note: "Hundreds of free notebooks on financial data, features and backtesting. The book is paid.",
      },
      {
        title: "Dixon & Coles (1997): Modelling association football scores",
        url: "https://doi.org/10.1111/1467-9876.00065",
        type: "article",
        free: false,
        note: "The paper behind the most famous football goal model. You'll implement a version of it.",
      },
      {
        title: "scikit-learn: cross-validation for time series",
        url: "https://scikit-learn.org/stable/modules/cross_validation.html#time-series-split",
        type: "docs",
        free: true,
        note: "TimeSeriesSplit and why ordinary k-fold is wrong for time-ordered data.",
      },
      {
        title: "scikit-learn: probability calibration",
        url: "https://scikit-learn.org/stable/modules/calibration.html",
        type: "docs",
        free: true,
        note: "For betting, probabilities must be calibrated, not just accurate.",
      },
      {
        title: "Kelly criterion (overview)",
        url: "https://en.wikipedia.org/wiki/Kelly_criterion",
        type: "article",
        free: true,
        note: "The maths of bet sizing, and why most people use a fraction of it.",
      },
      {
        title: "OANDA v20 REST API",
        url: "https://developer.oanda.com/rest-live-v20/introduction/",
        type: "docs",
        free: true,
        note: "Live forex prices and a free paper-trading (practice) account, for when you paper trade a model.",
      },
      {
        title: "MLflow documentation",
        url: "https://mlflow.org/docs/latest/index.html",
        type: "docs",
        free: true,
        note: "Track experiments, parameters and model versions.",
      },
      {
        title: "BeGambleAware",
        url: "https://www.begambleaware.org/",
        type: "article",
        free: true,
        note: "Free, confidential support. Building betting models is a great learning project; betting real money carries real risk.",
      },
    ],
  },
  {
    slug: "deep-learning",
    number: 7,
    title: "Deep Learning with PyTorch",
    tagline: "Neural networks from scratch, then PyTorch for images, sequences and transfer learning.",
    description:
      "Build a neural network in pure NumPy first, so nothing is magic. Then move to PyTorch in Google Colab (free GPUs): tensors, autograd, training loops, CNNs for images, sequence models and transformers, and fine-tuning pretrained models from Hugging Face.",
    weeks: "Weeks 27–32",
    outcomes: [
      "Implement forward and backward passes of a neural network by hand",
      "Write PyTorch training loops with validation and early stopping",
      "Train CNNs on images and use transfer learning",
      "Explain how RNNs, attention and transformers process sequences",
      "Know when deep learning beats gradient boosting, and when it doesn't",
    ],
    resources: [
      {
        title: "Practical Deep Learning for Coders (fast.ai)",
        url: "https://course.fast.ai/",
        type: "course",
        free: true,
        note: "Top-down, code-first, and free. One of the best deep learning courses ever made.",
      },
      {
        title: "Neural Networks: Zero to Hero (Andrej Karpathy)",
        url: "https://karpathy.ai/zero-to-hero.html",
        type: "video",
        free: true,
        note: "Build backpropagation, then a GPT, from scratch. The best way to really understand deep learning.",
      },
      {
        title: "PyTorch: Learn the Basics",
        url: "https://pytorch.org/tutorials/beginner/basics/intro.html",
        type: "docs",
        free: true,
        note: "The official tutorial series: tensors, datasets, models, autograd, training.",
      },
      {
        title: "Learn PyTorch for Deep Learning (Daniel Bourke)",
        url: "https://www.learnpytorch.io/",
        type: "book",
        free: true,
        note: "A free, beginner-friendly online book with lots of code.",
      },
      {
        title: "Dive into Deep Learning",
        url: "https://d2l.ai/",
        type: "book",
        free: true,
        note: "A free interactive book with runnable PyTorch code for every chapter.",
      },
      {
        title: "Understanding Deep Learning (Simon Prince)",
        url: "https://udlbook.github.io/udlbook/",
        type: "book",
        free: true,
        note: "A modern, clearly illustrated textbook. Free PDF.",
      },
      {
        title: "3Blue1Brown: Neural networks",
        url: "https://www.3blue1brown.com/topics/neural-networks",
        type: "video",
        free: true,
        note: "Visual explanations of backprop, attention and transformers.",
      },
      {
        title: "Deep Learning Specialization (DeepLearning.AI)",
        url: "https://www.coursera.org/specializations/deep-learning",
        type: "course",
        free: true,
        note: "Andrew Ng's structured deep learning course. Free to audit.",
      },
      {
        title: "Hugging Face Learn",
        url: "https://huggingface.co/learn",
        type: "course",
        free: true,
        note: "Free courses on transformers, LLMs and fine-tuning pretrained models.",
      },
    ],
  },
  {
    slug: "backend",
    number: 8,
    title: "Python for the Backend (FastAPI)",
    tagline: "Turn your models into web services other apps can use.",
    description:
      "How the web works, then FastAPI: routes, validation with Pydantic, databases with SQL and SQLAlchemy, authentication, testing, background jobs, and serving a trained ML model behind an API in Docker. FastAPI runs right here in your browser, and a companion project in the repo runs on your machine.",
    weeks: "Weeks 33–36",
    outcomes: [
      "Explain HTTP requests, responses, status codes and REST design",
      "Build and test a FastAPI service with validated inputs and outputs",
      "Store and query data with SQL and SQLAlchemy",
      "Protect endpoints with API keys or tokens",
      "Serve an ML model behind an API and ship it in a Docker container",
    ],
    resources: [
      {
        title: "FastAPI tutorial",
        url: "https://fastapi.tiangolo.com/tutorial/",
        type: "docs",
        free: true,
        note: "Famously good documentation. Work through the whole “Tutorial – User Guide”.",
      },
      {
        title: "Pydantic documentation",
        url: "https://docs.pydantic.dev/latest/",
        type: "docs",
        free: true,
        note: "Data validation with type hints. FastAPI is built on it.",
      },
      {
        title: "MDN: An overview of HTTP",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview",
        type: "docs",
        free: true,
        note: "How browsers and servers talk to each other.",
      },
      {
        title: "SQLBolt",
        url: "https://sqlbolt.com/",
        type: "practice",
        free: true,
        note: "Interactive SQL lessons. Every data and backend job expects SQL.",
      },
      {
        title: "SQLAlchemy 2.0 unified tutorial",
        url: "https://docs.sqlalchemy.org/en/20/tutorial/index.html",
        type: "docs",
        free: true,
        note: "The standard Python database toolkit.",
      },
      {
        title: "SQLModel",
        url: "https://sqlmodel.tiangolo.com/",
        type: "docs",
        free: true,
        note: "SQLAlchemy plus Pydantic, by the author of FastAPI. Very beginner-friendly.",
      },
      {
        title: "FastAPI in containers (Docker)",
        url: "https://fastapi.tiangolo.com/deployment/docker/",
        type: "docs",
        free: true,
        note: "How to package a FastAPI app with Docker. You already know Docker, so this will feel familiar.",
      },
      {
        title: "Full Stack FastAPI Template",
        url: "https://github.com/fastapi/full-stack-fastapi-template",
        type: "tool",
        free: true,
        note: "A production-style project to study: FastAPI, SQLModel, Postgres, Docker, tests and CI.",
      },
      {
        title: "Architecture Patterns with Python (Cosmic Python)",
        url: "https://www.cosmicpython.com/",
        type: "book",
        free: true,
        note: "Free online. How to structure larger backend applications.",
      },
      {
        title: "Django tutorial (alternative framework)",
        url: "https://docs.djangoproject.com/en/stable/intro/tutorial01/",
        type: "docs",
        free: true,
        note: "Django is the batteries-included alternative to FastAPI. Worth knowing it exists.",
      },
    ],
  },
  {
    slug: "capstone",
    number: 9,
    title: "Capstone & Career",
    tagline: "Ship an end-to-end ML system and become job-ready.",
    description:
      "Put everything together: a scheduled data pipeline, a trained and calibrated model, an honest walk-forward backtest, an API, monitoring and a write-up. Then the professional side: portfolio, Kaggle, MLOps, reading papers, interviews and what to learn next.",
    weeks: "Weeks 37–42+",
    outcomes: [
      "Design, build and deploy an end-to-end ML system",
      "Monitor a model in production and know when to retrain",
      "Present your work in a portfolio and a clear README",
      "Know the path from here to an ML engineering job",
    ],
    resources: [
      {
        title: "Made With ML (Goku Mohandas)",
        url: "https://madewithml.com/",
        type: "course",
        free: true,
        note: "Free course on building production ML systems: testing, MLOps, serving and CI/CD.",
      },
      {
        title: "Designing Machine Learning Systems (Chip Huyen)",
        url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/",
        type: "book",
        free: false,
        note: "The book on taking ML from notebook to production.",
      },
      {
        title: "Machine Learning Interviews (Chip Huyen)",
        url: "https://huyenchip.com/ml-interviews-book/",
        type: "book",
        free: true,
        note: "Free online. What ML interviews look like, and how to prepare.",
      },
      {
        title: "MLOps Zoomcamp (DataTalks.Club)",
        url: "https://github.com/DataTalksClub/mlops-zoomcamp",
        type: "course",
        free: true,
        note: "Free course: experiment tracking, orchestration, deployment and monitoring.",
      },
      {
        title: "Machine Learning Zoomcamp (DataTalks.Club)",
        url: "https://github.com/DataTalksClub/machine-learning-zoomcamp",
        type: "course",
        free: true,
        note: "Free course with projects you can add to your portfolio.",
      },
      {
        title: "Full Stack Deep Learning",
        url: "https://fullstackdeeplearning.com/",
        type: "course",
        free: true,
        note: "Lectures on building and shipping deep learning and LLM products.",
      },
      {
        title: "Kaggle competitions",
        url: "https://www.kaggle.com/competitions",
        type: "practice",
        free: true,
        note: "The fastest way to practise and to get public proof of your skills.",
      },
      {
        title: "Hugging Face Papers",
        url: "https://huggingface.co/papers",
        type: "article",
        free: true,
        note: "Trending ML research papers. Read one a week once you're comfortable.",
      },
      {
        title: "roadmap.sh: MLOps",
        url: "https://roadmap.sh/mlops",
        type: "article",
        free: true,
        note: "A map of the MLOps skills employers look for.",
      },
    ],
  },
];
